package com.habit.gold.core.designsystem.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

// Generated by scripts/generate_phosphor_icons.py from phosphor-icons/core assets.
internal object HabitGoldPhosphorIcons {
    object Regular {
        val ArrowsClockwise: ImageVector
            get() {
                if (arrowsClockwiseCache != null) {
                    return arrowsClockwiseCache!!
                }
                arrowsClockwiseCache = buildPhosphorIcon(
                    name = "ArrowsClockwise",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,48V96a8,8,0,0,1-8,8H168a8,8,0,0,1,0-16h28.69L182.06,73.37a79.56,79.56,0,0,0-56.13-23.43h-.45A79.52,79.52,0,0,0,69.59,72.71,8,8,0,0,1,58.41,61.27a96,96,0,0,1,135,.79L208,76.69V48a8,8,0,0,1,16,0ZM186.41,183.29a80,80,0,0,1-112.47-.66L59.31,168H88a8,8,0,0,0,0-16H40a8,8,0,0,0-8,8v48a8,8,0,0,0,16,0V179.31l14.63,14.63A95.43,95.43,0,0,0,130,222.06h.53a95.36,95.36,0,0,0,67.07-27.33,8,8,0,0,0-11.18-11.44Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowsClockwiseCache!!
            }
        private var arrowsClockwiseCache: ImageVector? = null

        val ArrowDown: ImageVector
            get() {
                if (arrowDownCache != null) {
                    return arrowDownCache!!
                }
                arrowDownCache = buildPhosphorIcon(
                    name = "ArrowDown",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M205.66,149.66l-72,72a8,8,0,0,1-11.32,0l-72-72a8,8,0,0,1,11.32-11.32L120,196.69V40a8,8,0,0,1,16,0V196.69l58.34-58.35a8,8,0,0,1,11.32,11.32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowDownCache!!
            }
        private var arrowDownCache: ImageVector? = null

        val ArrowUp: ImageVector
            get() {
                if (arrowUpCache != null) {
                    return arrowUpCache!!
                }
                arrowUpCache = buildPhosphorIcon(
                    name = "ArrowUp",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M205.66,117.66a8,8,0,0,1-11.32,0L136,59.31V216a8,8,0,0,1-16,0V59.31L61.66,117.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,205.66,117.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowUpCache!!
            }
        private var arrowUpCache: ImageVector? = null

        val Bank: ImageVector
            get() {
                if (bankCache != null) {
                    return bankCache!!
                }
                bankCache = buildPhosphorIcon(
                    name = "Bank",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M24,104H48v64H32a8,8,0,0,0,0,16H224a8,8,0,0,0,0-16H208V104h24a8,8,0,0,0,4.19-14.81l-104-64a8,8,0,0,0-8.38,0l-104,64A8,8,0,0,0,24,104Zm40,0H96v64H64Zm80,0v64H112V104Zm48,64H160V104h32ZM128,41.39,203.74,88H52.26ZM248,208a8,8,0,0,1-8,8H16a8,8,0,0,1,0-16H240A8,8,0,0,1,248,208Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return bankCache!!
            }
        private var bankCache: ImageVector? = null

        val Bell: ImageVector
            get() {
                if (bellCache != null) {
                    return bellCache!!
                }
                bellCache = buildPhosphorIcon(
                    name = "Bell",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M221.8,175.94C216.25,166.38,208,139.33,208,104a80,80,0,1,0-160,0c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.81a40,40,0,0,0,78.38,0H208a16,16,0,0,0,13.8-24.06ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216ZM48,184c7.7-13.24,16-43.92,16-80a64,64,0,1,1,128,0c0,36.05,8.28,66.73,16,80Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return bellCache!!
            }
        private var bellCache: ImageVector? = null

        val Calculator: ImageVector
            get() {
                if (calculatorCache != null) {
                    return calculatorCache!!
                }
                calculatorCache = buildPhosphorIcon(
                    name = "Calculator",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M80,120h96a8,8,0,0,0,8-8V64a8,8,0,0,0-8-8H80a8,8,0,0,0-8,8v48A8,8,0,0,0,80,120Zm8-48h80v32H88ZM200,24H56A16,16,0,0,0,40,40V216a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V40A16,16,0,0,0,200,24Zm0,192H56V40H200ZM100,148a12,12,0,1,1-12-12A12,12,0,0,1,100,148Zm40,0a12,12,0,1,1-12-12A12,12,0,0,1,140,148Zm40,0a12,12,0,1,1-12-12A12,12,0,0,1,180,148Zm-80,40a12,12,0,1,1-12-12A12,12,0,0,1,100,188Zm40,0a12,12,0,1,1-12-12A12,12,0,0,1,140,188Zm40,0a12,12,0,1,1-12-12A12,12,0,0,1,180,188Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return calculatorCache!!
            }
        private var calculatorCache: ImageVector? = null

        val CalendarBlank: ImageVector
            get() {
                if (calendarBlankCache != null) {
                    return calendarBlankCache!!
                }
                calendarBlankCache = buildPhosphorIcon(
                    name = "CalendarBlank",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M208,32H184V24a8,8,0,0,0-16,0v8H88V24a8,8,0,0,0-16,0v8H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM72,48v8a8,8,0,0,0,16,0V48h80v8a8,8,0,0,0,16,0V48h24V80H48V48ZM208,208H48V96H208V208Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return calendarBlankCache!!
            }
        private var calendarBlankCache: ImageVector? = null

        val CaretDown: ImageVector
            get() {
                if (caretDownCache != null) {
                    return caretDownCache!!
                }
                caretDownCache = buildPhosphorIcon(
                    name = "CaretDown",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return caretDownCache!!
            }
        private var caretDownCache: ImageVector? = null

        val CaretLeft: ImageVector
            get() {
                if (caretLeftCache != null) {
                    return caretLeftCache!!
                }
                caretLeftCache = buildPhosphorIcon(
                    name = "CaretLeft",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M165.66,202.34a8,8,0,0,1-11.32,11.32l-80-80a8,8,0,0,1,0-11.32l80-80a8,8,0,0,1,11.32,11.32L91.31,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return caretLeftCache!!
            }
        private var caretLeftCache: ImageVector? = null

        val CaretRight: ImageVector
            get() {
                if (caretRightCache != null) {
                    return caretRightCache!!
                }
                caretRightCache = buildPhosphorIcon(
                    name = "CaretRight",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M181.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L164.69,128,90.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,181.66,133.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return caretRightCache!!
            }
        private var caretRightCache: ImageVector? = null

        val CaretUp: ImageVector
            get() {
                if (caretUpCache != null) {
                    return caretUpCache!!
                }
                caretUpCache = buildPhosphorIcon(
                    name = "CaretUp",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M213.66,165.66a8,8,0,0,1-11.32,0L128,91.31,53.66,165.66a8,8,0,0,1-11.32-11.32l80-80a8,8,0,0,1,11.32,0l80,80A8,8,0,0,1,213.66,165.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return caretUpCache!!
            }
        private var caretUpCache: ImageVector? = null

        val ChatCircleDots: ImageVector
            get() {
                if (chatCircleDotsCache != null) {
                    return chatCircleDotsCache!!
                }
                chatCircleDotsCache = buildPhosphorIcon(
                    name = "ChatCircleDots",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128ZM84,116a12,12,0,1,0,12,12A12,12,0,0,0,84,116Zm88,0a12,12,0,1,0,12,12A12,12,0,0,0,172,116Zm60,12A104,104,0,0,1,79.12,219.82L45.07,231.17a16,16,0,0,1-20.24-20.24l11.35-34.05A104,104,0,1,1,232,128Zm-16,0A88,88,0,1,0,51.81,172.06a8,8,0,0,1,.66,6.54L40,216,77.4,203.53a7.85,7.85,0,0,1,2.53-.42,8,8,0,0,1,4,1.08A88,88,0,0,0,216,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return chatCircleDotsCache!!
            }
        private var chatCircleDotsCache: ImageVector? = null

        val Check: ImageVector
            get() {
                if (checkCache != null) {
                    return checkCache!!
                }
                checkCache = buildPhosphorIcon(
                    name = "Check",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return checkCache!!
            }
        private var checkCache: ImageVector? = null

        val CheckCircle: ImageVector
            get() {
                if (checkCircleCache != null) {
                    return checkCircleCache!!
                }
                checkCircleCache = buildPhosphorIcon(
                    name = "CheckCircle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34ZM232,128A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return checkCircleCache!!
            }
        private var checkCircleCache: ImageVector? = null

        val Circle: ImageVector
            get() {
                if (circleCache != null) {
                    return circleCache!!
                }
                circleCache = buildPhosphorIcon(
                    name = "Circle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return circleCache!!
            }
        private var circleCache: ImageVector? = null

        val Clock: ImageVector
            get() {
                if (clockCache != null) {
                    return clockCache!!
                }
                clockCache = buildPhosphorIcon(
                    name = "Clock",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm64-88a8,8,0,0,1-8,8H128a8,8,0,0,1-8-8V72a8,8,0,0,1,16,0v48h48A8,8,0,0,1,192,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return clockCache!!
            }
        private var clockCache: ImageVector? = null

        val ClockCounterClockwise: ImageVector
            get() {
                if (clockCounterClockwiseCache != null) {
                    return clockCounterClockwiseCache!!
                }
                clockCounterClockwiseCache = buildPhosphorIcon(
                    name = "ClockCounterClockwise",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M136,80v43.47l36.12,21.67a8,8,0,0,1-8.24,13.72l-40-24A8,8,0,0,1,120,128V80a8,8,0,0,1,16,0Zm-8-48A95.44,95.44,0,0,0,60.08,60.15C52.81,67.51,46.35,74.59,40,82V64a8,8,0,0,0-16,0v40a8,8,0,0,0,8,8H72a8,8,0,0,0,0-16H49c7.15-8.42,14.27-16.35,22.39-24.57a80,80,0,1,1,1.66,114.75,8,8,0,1,0-11,11.64A96,96,0,1,0,128,32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return clockCounterClockwiseCache!!
            }
        private var clockCounterClockwiseCache: ImageVector? = null

        val Coins: ImageVector
            get() {
                if (coinsCache != null) {
                    return coinsCache!!
                }
                coinsCache = buildPhosphorIcon(
                    name = "Coins",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M184,89.57V84c0-25.08-37.83-44-88-44S8,58.92,8,84v40c0,20.89,26.25,37.49,64,42.46V172c0,25.08,37.83,44,88,44s88-18.92,88-44V132C248,111.3,222.58,94.68,184,89.57ZM232,132c0,13.22-30.79,28-72,28-3.73,0-7.43-.13-11.08-.37C170.49,151.77,184,139,184,124V105.74C213.87,110.19,232,122.27,232,132ZM72,150.25V126.46A183.74,183.74,0,0,0,96,128a183.74,183.74,0,0,0,24-1.54v23.79A163,163,0,0,1,96,152,163,163,0,0,1,72,150.25Zm96-40.32V124c0,8.39-12.41,17.4-32,22.87V123.5C148.91,120.37,159.84,115.71,168,109.93ZM96,56c41.21,0,72,14.78,72,28s-30.79,28-72,28S24,97.22,24,84,54.79,56,96,56ZM24,124V109.93c8.16,5.78,19.09,10.44,32,13.57v23.37C36.41,141.4,24,132.39,24,124Zm64,48v-4.17c2.63.1,5.29.17,8,.17,3.88,0,7.67-.13,11.39-.35A121.92,121.92,0,0,0,120,171.41v23.46C100.41,189.4,88,180.39,88,172Zm48,26.25V174.4a179.48,179.48,0,0,0,24,1.6,183.74,183.74,0,0,0,24-1.54v23.79a165.45,165.45,0,0,1-48,0Zm64-3.38V171.5c12.91-3.13,23.84-7.79,32-13.57V172C232,180.39,219.59,189.4,200,194.87Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return coinsCache!!
            }
        private var coinsCache: ImageVector? = null

        val Copy: ImageVector
            get() {
                if (copyCache != null) {
                    return copyCache!!
                }
                copyCache = buildPhosphorIcon(
                    name = "Copy",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M216,32H88a8,8,0,0,0-8,8V80H40a8,8,0,0,0-8,8V216a8,8,0,0,0,8,8H168a8,8,0,0,0,8-8V176h40a8,8,0,0,0,8-8V40A8,8,0,0,0,216,32ZM160,208H48V96H160Zm48-48H176V88a8,8,0,0,0-8-8H96V48H208Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return copyCache!!
            }
        private var copyCache: ImageVector? = null

        val CreditCard: ImageVector
            get() {
                if (creditCardCache != null) {
                    return creditCardCache!!
                }
                creditCardCache = buildPhosphorIcon(
                    name = "CreditCard",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,48H32A16,16,0,0,0,16,64V192a16,16,0,0,0,16,16H224a16,16,0,0,0,16-16V64A16,16,0,0,0,224,48Zm0,16V88H32V64Zm0,128H32V104H224v88Zm-16-24a8,8,0,0,1-8,8H168a8,8,0,0,1,0-16h32A8,8,0,0,1,208,168Zm-64,0a8,8,0,0,1-8,8H120a8,8,0,0,1,0-16h16A8,8,0,0,1,144,168Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return creditCardCache!!
            }
        private var creditCardCache: ImageVector? = null

        val CurrencyInr: ImageVector
            get() {
                if (currencyInrCache != null) {
                    return currencyInrCache!!
                }
                currencyInrCache = buildPhosphorIcon(
                    name = "CurrencyInr",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M208,80a8,8,0,0,1-8,8H167.85c.09,1.32.15,2.65.15,4a60.07,60.07,0,0,1-60,60H92.69l72.69,66.08a8,8,0,1,1-10.76,11.84l-88-80A8,8,0,0,1,72,136h36a44.05,44.05,0,0,0,44-44c0-1.35-.07-2.68-.19-4H72a8,8,0,0,1,0-16h75.17A44,44,0,0,0,108,48H72a8,8,0,0,1,0-16H200a8,8,0,0,1,0,16H148.74a60.13,60.13,0,0,1,15.82,24H200A8,8,0,0,1,208,80Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return currencyInrCache!!
            }
        private var currencyInrCache: ImageVector? = null

        val DownloadSimple: ImageVector
            get() {
                if (downloadSimpleCache != null) {
                    return downloadSimpleCache!!
                }
                downloadSimpleCache = buildPhosphorIcon(
                    name = "DownloadSimple",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,144v64a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V144a8,8,0,0,1,16,0v56H208V144a8,8,0,0,1,16,0Zm-101.66,5.66a8,8,0,0,0,11.32,0l40-40a8,8,0,0,0-11.32-11.32L136,124.69V32a8,8,0,0,0-16,0v92.69L93.66,98.34a8,8,0,0,0-11.32,11.32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return downloadSimpleCache!!
            }
        private var downloadSimpleCache: ImageVector? = null

        val Envelope: ImageVector
            get() {
                if (envelopeCache != null) {
                    return envelopeCache!!
                }
                envelopeCache = buildPhosphorIcon(
                    name = "Envelope",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,48H32a8,8,0,0,0-8,8V192a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A8,8,0,0,0,224,48Zm-96,85.15L52.57,64H203.43ZM98.71,128,40,181.81V74.19Zm11.84,10.85,12,11.05a8,8,0,0,0,10.82,0l12-11.05,58,53.15H52.57ZM157.29,128,216,74.18V181.82Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return envelopeCache!!
            }
        private var envelopeCache: ImageVector? = null

        val Eye: ImageVector
            get() {
                if (eyeCache != null) {
                    return eyeCache!!
                }
                eyeCache = buildPhosphorIcon(
                    name = "Eye",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M247.31,124.76c-.35-.79-8.82-19.58-27.65-38.41C194.57,61.26,162.88,48,128,48S61.43,61.26,36.34,86.35C17.51,105.18,9,124,8.69,124.76a8,8,0,0,0,0,6.5c.35.79,8.82,19.57,27.65,38.4C61.43,194.74,93.12,208,128,208s66.57-13.26,91.66-38.34c18.83-18.83,27.3-37.61,27.65-38.4A8,8,0,0,0,247.31,124.76ZM128,192c-30.78,0-57.67-11.19-79.93-33.25A133.47,133.47,0,0,1,25,128,133.33,133.33,0,0,1,48.07,97.25C70.33,75.19,97.22,64,128,64s57.67,11.19,79.93,33.25A133.46,133.46,0,0,1,231.05,128C223.84,141.46,192.43,192,128,192Zm0-112a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return eyeCache!!
            }
        private var eyeCache: ImageVector? = null

        val EyeSlash: ImageVector
            get() {
                if (eyeSlashCache != null) {
                    return eyeSlashCache!!
                }
                eyeSlashCache = buildPhosphorIcon(
                    name = "EyeSlash",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M53.92,34.62A8,8,0,1,0,42.08,45.38L61.32,66.55C25,88.84,9.38,123.2,8.69,124.76a8,8,0,0,0,0,6.5c.35.79,8.82,19.57,27.65,38.4C61.43,194.74,93.12,208,128,208a127.11,127.11,0,0,0,52.07-10.83l22,24.21a8,8,0,1,0,11.84-10.76Zm47.33,75.84,41.67,45.85a32,32,0,0,1-41.67-45.85ZM128,192c-30.78,0-57.67-11.19-79.93-33.25A133.16,133.16,0,0,1,25,128c4.69-8.79,19.66-33.39,47.35-49.38l18,19.75a48,48,0,0,0,63.66,70l14.73,16.2A112,112,0,0,1,128,192Zm6-95.43a8,8,0,0,1,3-15.72,48.16,48.16,0,0,1,38.77,42.64,8,8,0,0,1-7.22,8.71,6.39,6.39,0,0,1-.75,0,8,8,0,0,1-8-7.26A32.09,32.09,0,0,0,134,96.57Zm113.28,34.69c-.42.94-10.55,23.37-33.36,43.8a8,8,0,1,1-10.67-11.92A132.77,132.77,0,0,0,231.05,128a133.15,133.15,0,0,0-23.12-30.77C185.67,75.19,158.78,64,128,64a118.37,118.37,0,0,0-19.36,1.57A8,8,0,1,1,106,49.79,134,134,0,0,1,128,48c34.88,0,66.57,13.26,91.66,38.35,18.83,18.83,27.3,37.62,27.65,38.41A8,8,0,0,1,247.31,131.26Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return eyeSlashCache!!
            }
        private var eyeSlashCache: ImageVector? = null

        val FileText: ImageVector
            get() {
                if (fileTextCache != null) {
                    return fileTextCache!!
                }
                fileTextCache = buildPhosphorIcon(
                    name = "FileText",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M213.66,82.34l-56-56A8,8,0,0,0,152,24H56A16,16,0,0,0,40,40V216a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V88A8,8,0,0,0,213.66,82.34ZM160,51.31,188.69,80H160ZM200,216H56V40h88V88a8,8,0,0,0,8,8h48V216Zm-32-80a8,8,0,0,1-8,8H96a8,8,0,0,1,0-16h64A8,8,0,0,1,168,136Zm0,32a8,8,0,0,1-8,8H96a8,8,0,0,1,0-16h64A8,8,0,0,1,168,168Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return fileTextCache!!
            }
        private var fileTextCache: ImageVector? = null

        val Fingerprint: ImageVector
            get() {
                if (fingerprintCache != null) {
                    return fingerprintCache!!
                }
                fingerprintCache = buildPhosphorIcon(
                    name = "Fingerprint",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M72,128a134.63,134.63,0,0,1-14.16,60.47,8,8,0,1,1-14.32-7.12A118.8,118.8,0,0,0,56,128,71.73,71.73,0,0,1,83,71.8,8,8,0,1,1,93,84.29,55.76,55.76,0,0,0,72,128Zm56-8a8,8,0,0,0-8,8,184.12,184.12,0,0,1-23,89.1,8,8,0,0,0,14,7.76A200.19,200.19,0,0,0,136,128,8,8,0,0,0,128,120Zm0-32a40,40,0,0,0-40,40,8,8,0,0,0,16,0,24,24,0,0,1,48,0,214.09,214.09,0,0,1-20.51,92A8,8,0,1,0,146,226.83,230,230,0,0,0,168,128,40,40,0,0,0,128,88Zm0-64A104.11,104.11,0,0,0,24,128a87.76,87.76,0,0,1-5,29.33,8,8,0,0,0,15.09,5.33A103.9,103.9,0,0,0,40,128a88,88,0,0,1,176,0,282.24,282.24,0,0,1-5.29,54.45,8,8,0,0,0,6.3,9.4,8.22,8.22,0,0,0,1.55.15,8,8,0,0,0,7.84-6.45A298.37,298.37,0,0,0,232,128,104.12,104.12,0,0,0,128,24ZM94.4,152.17A8,8,0,0,0,85,158.42a151,151,0,0,1-17.21,45.44,8,8,0,0,0,13.86,8,166.67,166.67,0,0,0,19-50.25A8,8,0,0,0,94.4,152.17ZM128,56a72.85,72.85,0,0,0-9,.56,8,8,0,0,0,2,15.87A56.08,56.08,0,0,1,184,128a252.12,252.12,0,0,1-1.92,31A8,8,0,0,0,189,168a8.39,8.39,0,0,0,1,.06,8,8,0,0,0,7.92-7,266.48,266.48,0,0,0,2-33A72.08,72.08,0,0,0,128,56Zm57.93,128.25a8,8,0,0,0-9.75,5.75c-1.46,5.69-3.15,11.4-5,17a8,8,0,0,0,5,10.13,7.88,7.88,0,0,0,2.55.42,8,8,0,0,0,7.58-5.46c2-5.92,3.79-12,5.35-18.05A8,8,0,0,0,185.94,184.26Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return fingerprintCache!!
            }
        private var fingerprintCache: ImageVector? = null

        val Gift: ImageVector
            get() {
                if (giftCache != null) {
                    return giftCache!!
                }
                giftCache = buildPhosphorIcon(
                    name = "Gift",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M216,72H180.92c.39-.33.79-.65,1.17-1A29.53,29.53,0,0,0,192,49.57,32.62,32.62,0,0,0,158.44,16,29.53,29.53,0,0,0,137,25.91a54.94,54.94,0,0,0-9,14.48,54.94,54.94,0,0,0-9-14.48A29.53,29.53,0,0,0,97.56,16,32.62,32.62,0,0,0,64,49.57,29.53,29.53,0,0,0,73.91,71c.38.33.78.65,1.17,1H40A16,16,0,0,0,24,88v32a16,16,0,0,0,16,16v64a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V136a16,16,0,0,0,16-16V88A16,16,0,0,0,216,72ZM149,36.51a13.69,13.69,0,0,1,10-4.5h.49A16.62,16.62,0,0,1,176,49.08a13.69,13.69,0,0,1-4.5,10c-9.49,8.4-25.24,11.36-35,12.4C137.7,60.89,141,45.5,149,36.51Zm-64.09.36A16.63,16.63,0,0,1,96.59,32h.49a13.69,13.69,0,0,1,10,4.5c8.39,9.48,11.35,25.2,12.39,34.92-9.72-1-25.44-4-34.92-12.39a13.69,13.69,0,0,1-4.5-10A16.6,16.6,0,0,1,84.87,36.87ZM40,88h80v32H40Zm16,48h64v64H56Zm144,64H136V136h64Zm16-80H136V88h80v32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return giftCache!!
            }
        private var giftCache: ImageVector? = null

        val HandCoins: ImageVector
            get() {
                if (handCoinsCache != null) {
                    return handCoinsCache!!
                }
                handCoinsCache = buildPhosphorIcon(
                    name = "HandCoins",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M230.33,141.06a24.43,24.43,0,0,0-21.24-4.23l-41.84,9.62A28,28,0,0,0,140,112H89.94a31.82,31.82,0,0,0-22.63,9.37L44.69,144H16A16,16,0,0,0,0,160v40a16,16,0,0,0,16,16H120a7.93,7.93,0,0,0,1.94-.24l64-16a6.94,6.94,0,0,0,1.19-.4L226,182.82l.44-.2a24.6,24.6,0,0,0,3.93-41.56ZM16,160H40v40H16Zm203.43,8.21-38,16.18L119,200H56V155.31l22.63-22.62A15.86,15.86,0,0,1,89.94,128H140a12,12,0,0,1,0,24H112a8,8,0,0,0,0,16h32a8.32,8.32,0,0,0,1.79-.2l67-15.41.31-.08a8.6,8.6,0,0,1,6.3,15.9ZM164,96a36,36,0,0,0,5.9-.48,36,36,0,1,0,28.22-47A36,36,0,1,0,164,96Zm60-12a20,20,0,1,1-20-20A20,20,0,0,1,224,84ZM164,40a20,20,0,0,1,19.25,14.61,36,36,0,0,0-15,24.93A20.42,20.42,0,0,1,164,80a20,20,0,0,1,0-40Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return handCoinsCache!!
            }
        private var handCoinsCache: ImageVector? = null

        val Headset: ImageVector
            get() {
                if (headsetCache != null) {
                    return headsetCache!!
                }
                headsetCache = buildPhosphorIcon(
                    name = "Headset",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M201.89,54.66A103.43,103.43,0,0,0,128.79,24H128A104,104,0,0,0,24,128v56a24,24,0,0,0,24,24H64a24,24,0,0,0,24-24V144a24,24,0,0,0-24-24H40.36A88.12,88.12,0,0,1,190.54,65.93,87.39,87.39,0,0,1,215.65,120H192a24,24,0,0,0-24,24v40a24,24,0,0,0,24,24h24a24,24,0,0,1-24,24H136a8,8,0,0,0,0,16h56a40,40,0,0,0,40-40V128A103.41,103.41,0,0,0,201.89,54.66ZM64,136a8,8,0,0,1,8,8v40a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V136Zm128,56a8,8,0,0,1-8-8V144a8,8,0,0,1,8-8h24v56Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return headsetCache!!
            }
        private var headsetCache: ImageVector? = null

        val Heart: ImageVector
            get() {
                if (heartCache != null) {
                    return heartCache!!
                }
                heartCache = buildPhosphorIcon(
                    name = "Heart",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M178,40c-20.65,0-38.73,8.88-50,23.89C116.73,48.88,98.65,40,78,40a62.07,62.07,0,0,0-62,62c0,70,103.79,126.66,108.21,129a8,8,0,0,0,7.58,0C136.21,228.66,240,172,240,102A62.07,62.07,0,0,0,178,40ZM128,214.8C109.74,204.16,32,155.69,32,102A46.06,46.06,0,0,1,78,56c19.45,0,35.78,10.36,42.6,27a8,8,0,0,0,14.8,0c6.82-16.67,23.15-27,42.6-27a46.06,46.06,0,0,1,46,46C224,155.61,146.24,204.15,128,214.8Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return heartCache!!
            }
        private var heartCache: ImageVector? = null

        val House: ImageVector
            get() {
                if (houseCache != null) {
                    return houseCache!!
                }
                houseCache = buildPhosphorIcon(
                    name = "House",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return houseCache!!
            }
        private var houseCache: ImageVector? = null

        val HouseLine: ImageVector
            get() {
                if (houseLineCache != null) {
                    return houseLineCache!!
                }
                houseLineCache = buildPhosphorIcon(
                    name = "HouseLine",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M240,208H224V136l2.34,2.34A8,8,0,0,0,237.66,127L139.31,28.68a16,16,0,0,0-22.62,0L18.34,127a8,8,0,0,0,11.32,11.31L32,136v72H16a8,8,0,0,0,0,16H240a8,8,0,0,0,0-16ZM48,120l80-80,80,80v88H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48Zm96,88H112V160h32Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return houseLineCache!!
            }
        private var houseLineCache: ImageVector? = null

        val IdentificationBadge: ImageVector
            get() {
                if (identificationBadgeCache != null) {
                    return identificationBadgeCache!!
                }
                identificationBadgeCache = buildPhosphorIcon(
                    name = "IdentificationBadge",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M75.19,198.4a8,8,0,0,0,11.21-1.6,52,52,0,0,1,83.2,0,8,8,0,1,0,12.8-9.6A67.88,67.88,0,0,0,155,165.51a40,40,0,1,0-53.94,0A67.88,67.88,0,0,0,73.6,187.2,8,8,0,0,0,75.19,198.4ZM128,112a24,24,0,1,1-24,24A24,24,0,0,1,128,112Zm72-88H56A16,16,0,0,0,40,40V216a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V40A16,16,0,0,0,200,24Zm0,192H56V40H200ZM88,64a8,8,0,0,1,8-8h64a8,8,0,0,1,0,16H96A8,8,0,0,1,88,64Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return identificationBadgeCache!!
            }
        private var identificationBadgeCache: ImageVector? = null

        val Info: ImageVector
            get() {
                if (infoCache != null) {
                    return infoCache!!
                }
                infoCache = buildPhosphorIcon(
                    name = "Info",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm16-40a8,8,0,0,1-8,8,16,16,0,0,1-16-16V128a8,8,0,0,1,0-16,16,16,0,0,1,16,16v40A8,8,0,0,1,144,176ZM112,84a12,12,0,1,1,12,12A12,12,0,0,1,112,84Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return infoCache!!
            }
        private var infoCache: ImageVector? = null

        val Lightbulb: ImageVector
            get() {
                if (lightbulbCache != null) {
                    return lightbulbCache!!
                }
                lightbulbCache = buildPhosphorIcon(
                    name = "Lightbulb",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M176,232a8,8,0,0,1-8,8H88a8,8,0,0,1,0-16h80A8,8,0,0,1,176,232Zm40-128a87.55,87.55,0,0,1-33.64,69.21A16.24,16.24,0,0,0,176,186v6a16,16,0,0,1-16,16H96a16,16,0,0,1-16-16v-6a16,16,0,0,0-6.23-12.66A87.59,87.59,0,0,1,40,104.49C39.74,56.83,78.26,17.14,125.88,16A88,88,0,0,1,216,104Zm-16,0a72,72,0,0,0-73.74-72c-39,.92-70.47,33.39-70.26,72.39a71.65,71.65,0,0,0,27.64,56.3A32,32,0,0,1,96,186v6h64v-6a32.15,32.15,0,0,1,12.47-25.35A71.65,71.65,0,0,0,200,104Zm-16.11-9.34a57.6,57.6,0,0,0-46.56-46.55,8,8,0,0,0-2.66,15.78c16.57,2.79,30.63,16.85,33.44,33.45A8,8,0,0,0,176,104a9,9,0,0,0,1.35-.11A8,8,0,0,0,183.89,94.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return lightbulbCache!!
            }
        private var lightbulbCache: ImageVector? = null

        val Lock: ImageVector
            get() {
                if (lockCache != null) {
                    return lockCache!!
                }
                lockCache = buildPhosphorIcon(
                    name = "Lock",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M208,80H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80ZM96,56a32,32,0,0,1,64,0V80H96ZM208,208H48V96H208V208Zm-68-56a12,12,0,1,1-12-12A12,12,0,0,1,140,152Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return lockCache!!
            }
        private var lockCache: ImageVector? = null

        val MagnifyingGlass: ImageVector
            get() {
                if (magnifyingGlassCache != null) {
                    return magnifyingGlassCache!!
                }
                magnifyingGlassCache = buildPhosphorIcon(
                    name = "MagnifyingGlass",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return magnifyingGlassCache!!
            }
        private var magnifyingGlassCache: ImageVector? = null

        val MapPin: ImageVector
            get() {
                if (mapPinCache != null) {
                    return mapPinCache!!
                }
                mapPinCache = buildPhosphorIcon(
                    name = "MapPin",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,64a40,40,0,1,0,40,40A40,40,0,0,0,128,64Zm0,64a24,24,0,1,1,24-24A24,24,0,0,1,128,128Zm0-112a88.1,88.1,0,0,0-88,88c0,31.4,14.51,64.68,42,96.25a254.19,254.19,0,0,0,41.45,38.3,8,8,0,0,0,9.18,0A254.19,254.19,0,0,0,174,200.25c27.45-31.57,42-64.85,42-96.25A88.1,88.1,0,0,0,128,16Zm0,206c-16.53-13-72-60.75-72-118a72,72,0,0,1,144,0C200,161.23,144.53,209,128,222Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return mapPinCache!!
            }
        private var mapPinCache: ImageVector? = null

        val Medal: ImageVector
            get() {
                if (medalCache != null) {
                    return medalCache!!
                }
                medalCache = buildPhosphorIcon(
                    name = "Medal",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M216,96A88,88,0,1,0,72,163.83V240a8,8,0,0,0,11.58,7.16L128,225l44.43,22.21A8.07,8.07,0,0,0,176,248a8,8,0,0,0,8-8V163.83A87.85,87.85,0,0,0,216,96ZM56,96a72,72,0,1,1,72,72A72.08,72.08,0,0,1,56,96ZM168,227.06l-36.43-18.21a8,8,0,0,0-7.16,0L88,227.06V174.37a87.89,87.89,0,0,0,80,0ZM128,152A56,56,0,1,0,72,96,56.06,56.06,0,0,0,128,152Zm0-96A40,40,0,1,1,88,96,40,40,0,0,1,128,56Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return medalCache!!
            }
        private var medalCache: ImageVector? = null

        val Minus: ImageVector
            get() {
                if (minusCache != null) {
                    return minusCache!!
                }
                minusCache = buildPhosphorIcon(
                    name = "Minus",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return minusCache!!
            }
        private var minusCache: ImageVector? = null

        val PencilSimple: ImageVector
            get() {
                if (pencilSimpleCache != null) {
                    return pencilSimpleCache!!
                }
                pencilSimpleCache = buildPhosphorIcon(
                    name = "PencilSimple",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM92.69,208H48V163.31l88-88L180.69,120ZM192,108.68,147.31,64l24-24L216,84.68Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return pencilSimpleCache!!
            }
        private var pencilSimpleCache: ImageVector? = null

        val Phone: ImageVector
            get() {
                if (phoneCache != null) {
                    return phoneCache!!
                }
                phoneCache = buildPhosphorIcon(
                    name = "Phone",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M222.37,158.46l-47.11-21.11-.13-.06a16,16,0,0,0-15.17,1.4,8.12,8.12,0,0,0-.75.56L134.87,160c-15.42-7.49-31.34-23.29-38.83-38.51l20.78-24.71c.2-.25.39-.5.57-.77a16,16,0,0,0,1.32-15.06l0-.12L97.54,33.64a16,16,0,0,0-16.62-9.52A56.26,56.26,0,0,0,32,80c0,79.4,64.6,144,144,144a56.26,56.26,0,0,0,55.88-48.92A16,16,0,0,0,222.37,158.46ZM176,208A128.14,128.14,0,0,1,48,80,40.2,40.2,0,0,1,82.87,40a.61.61,0,0,0,0,.12l21,47L83.2,111.86a6.13,6.13,0,0,0-.57.77,16,16,0,0,0-1,15.7c9.06,18.53,27.73,37.06,46.46,46.11a16,16,0,0,0,15.75-1.14,8.44,8.44,0,0,0,.74-.56L168.89,152l47,21.05h0s.08,0,.11,0A40.21,40.21,0,0,1,176,208Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return phoneCache!!
            }
        private var phoneCache: ImageVector? = null

        val PiggyBank: ImageVector
            get() {
                if (piggyBankCache != null) {
                    return piggyBankCache!!
                }
                piggyBankCache = buildPhosphorIcon(
                    name = "PiggyBank",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M192,116a12,12,0,1,1-12-12A12,12,0,0,1,192,116ZM152,64H112a8,8,0,0,0,0,16h40a8,8,0,0,0,0-16Zm96,48v32a24,24,0,0,1-24,24h-2.36l-16.21,45.38A16,16,0,0,1,190.36,224H177.64a16,16,0,0,1-15.07-10.62L160.65,208h-57.3l-1.92,5.38A16,16,0,0,1,86.36,224H73.64a16,16,0,0,1-15.07-10.62L46,178.22a87.69,87.69,0,0,1-21.44-48.38A16,16,0,0,0,16,144a8,8,0,0,1-16,0,32,32,0,0,1,24.28-31A88.12,88.12,0,0,1,112,32H216a8,8,0,0,1,0,16H194.61a87.93,87.93,0,0,1,30.17,37c.43,1,.85,2,1.25,3A24,24,0,0,1,248,112Zm-16,0a8,8,0,0,0-8-8h-3.66a8,8,0,0,1-7.64-5.6A71.9,71.9,0,0,0,144,48H112A72,72,0,0,0,58.91,168.64a8,8,0,0,1,1.64,2.71L73.64,208H86.36l3.82-10.69A8,8,0,0,1,97.71,192h68.58a8,8,0,0,1,7.53,5.31L177.64,208h12.72l18.11-50.69A8,8,0,0,1,216,152h8a8,8,0,0,0,8-8Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return piggyBankCache!!
            }
        private var piggyBankCache: ImageVector? = null

        val Plus: ImageVector
            get() {
                if (plusCache != null) {
                    return plusCache!!
                }
                plusCache = buildPhosphorIcon(
                    name = "Plus",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return plusCache!!
            }
        private var plusCache: ImageVector? = null

        val QrCode: ImageVector
            get() {
                if (qrCodeCache != null) {
                    return qrCodeCache!!
                }
                qrCodeCache = buildPhosphorIcon(
                    name = "QrCode",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M104,40H56A16,16,0,0,0,40,56v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V56A16,16,0,0,0,104,40Zm0,64H56V56h48v48Zm0,32H56a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V152A16,16,0,0,0,104,136Zm0,64H56V152h48v48ZM200,40H152a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V56A16,16,0,0,0,200,40Zm0,64H152V56h48v48Zm-64,72V144a8,8,0,0,1,16,0v32a8,8,0,0,1-16,0Zm80-16a8,8,0,0,1-8,8H184v40a8,8,0,0,1-8,8H144a8,8,0,0,1,0-16h24V144a8,8,0,0,1,16,0v8h24A8,8,0,0,1,216,160Zm0,32v16a8,8,0,0,1-16,0V192a8,8,0,0,1,16,0Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return qrCodeCache!!
            }
        private var qrCodeCache: ImageVector? = null

        val Question: ImageVector
            get() {
                if (questionCache != null) {
                    return questionCache!!
                }
                questionCache = buildPhosphorIcon(
                    name = "Question",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M140,180a12,12,0,1,1-12-12A12,12,0,0,1,140,180ZM128,72c-22.06,0-40,16.15-40,36v4a8,8,0,0,0,16,0v-4c0-11,10.77-20,24-20s24,9,24,20-10.77,20-24,20a8,8,0,0,0-8,8v8a8,8,0,0,0,16,0v-.72c18.24-3.35,32-17.9,32-35.28C168,88.15,150.06,72,128,72Zm104,56A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return questionCache!!
            }
        private var questionCache: ImageVector? = null

        val SealCheck: ImageVector
            get() {
                if (sealCheckCache != null) {
                    return sealCheckCache!!
                }
                sealCheckCache = buildPhosphorIcon(
                    name = "SealCheck",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M225.86,102.82c-3.77-3.94-7.67-8-9.14-11.57-1.36-3.27-1.44-8.69-1.52-13.94-.15-9.76-.31-20.82-8-28.51s-18.75-7.85-28.51-8c-5.25-.08-10.67-.16-13.94-1.52-3.56-1.47-7.63-5.37-11.57-9.14C146.28,23.51,138.44,16,128,16s-18.27,7.51-25.18,14.14c-3.94,3.77-8,7.67-11.57,9.14C88,40.64,82.56,40.72,77.31,40.8c-9.76.15-20.82.31-28.51,8S41,67.55,40.8,77.31c-.08,5.25-.16,10.67-1.52,13.94-1.47,3.56-5.37,7.63-9.14,11.57C23.51,109.72,16,117.56,16,128s7.51,18.27,14.14,25.18c3.77,3.94,7.67,8,9.14,11.57,1.36,3.27,1.44,8.69,1.52,13.94.15,9.76.31,20.82,8,28.51s18.75,7.85,28.51,8c5.25.08,10.67.16,13.94,1.52,3.56,1.47,7.63,5.37,11.57,9.14C109.72,232.49,117.56,240,128,240s18.27-7.51,25.18-14.14c3.94-3.77,8-7.67,11.57-9.14,3.27-1.36,8.69-1.44,13.94-1.52,9.76-.15,20.82-.31,28.51-8s7.85-18.75,8-28.51c.08-5.25.16-10.67,1.52-13.94,1.47-3.56,5.37-7.63,9.14-11.57C232.49,146.28,240,138.44,240,128S232.49,109.73,225.86,102.82Zm-11.55,39.29c-4.79,5-9.75,10.17-12.38,16.52-2.52,6.1-2.63,13.07-2.73,19.82-.1,7-.21,14.33-3.32,17.43s-10.39,3.22-17.43,3.32c-6.75.1-13.72.21-19.82,2.73-6.35,2.63-11.52,7.59-16.52,12.38S132,224,128,224s-9.15-4.92-14.11-9.69-10.17-9.75-16.52-12.38c-6.1-2.52-13.07-2.63-19.82-2.73-7-.1-14.33-.21-17.43-3.32s-3.22-10.39-3.32-17.43c-.1-6.75-.21-13.72-2.73-19.82-2.63-6.35-7.59-11.52-12.38-16.52S32,132,32,128s4.92-9.15,9.69-14.11,9.75-10.17,12.38-16.52c2.52-6.1,2.63-13.07,2.73-19.82.1-7,.21-14.33,3.32-17.43S70.51,56.9,77.55,56.8c6.75-.1,13.72-.21,19.82-2.73,6.35-2.63,11.52-7.59,16.52-12.38S124,32,128,32s9.15,4.92,14.11,9.69,10.17,9.75,16.52,12.38c6.1,2.52,13.07,2.63,19.82,2.73,7,.1,14.33.21,17.43,3.32s3.22,10.39,3.32,17.43c.1,6.75.21,13.72,2.73,19.82,2.63,6.35,7.59,11.52,12.38,16.52S224,124,224,128,219.08,137.15,214.31,142.11ZM173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return sealCheckCache!!
            }
        private var sealCheckCache: ImageVector? = null

        val ShieldCheck: ImageVector
            get() {
                if (shieldCheckCache != null) {
                    return shieldCheckCache!!
                }
                shieldCheckCache = buildPhosphorIcon(
                    name = "ShieldCheck",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M208,40H48A16,16,0,0,0,32,56v56c0,52.72,25.52,84.67,46.93,102.19,23.06,18.86,46,25.26,47,25.53a8,8,0,0,0,4.2,0c1-.27,23.91-6.67,47-25.53C198.48,196.67,224,164.72,224,112V56A16,16,0,0,0,208,40Zm0,72c0,37.07-13.66,67.16-40.6,89.42A129.3,129.3,0,0,1,128,223.62a128.25,128.25,0,0,1-38.92-21.81C61.82,179.51,48,149.3,48,112l0-56,160,0ZM82.34,141.66a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35a8,8,0,0,1,11.32,11.32l-56,56a8,8,0,0,1-11.32,0Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return shieldCheckCache!!
            }
        private var shieldCheckCache: ImageVector? = null

        val ShoppingCart: ImageVector
            get() {
                if (shoppingCartCache != null) {
                    return shoppingCartCache!!
                }
                shoppingCartCache = buildPhosphorIcon(
                    name = "ShoppingCart",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M230.14,58.87A8,8,0,0,0,224,56H62.68L56.6,22.57A8,8,0,0,0,48.73,16H24a8,8,0,0,0,0,16h18L67.56,172.29a24,24,0,0,0,5.33,11.27,28,28,0,1,0,44.4,8.44h45.42A27.75,27.75,0,0,0,160,204a28,28,0,1,0,28-28H91.17a8,8,0,0,1-7.87-6.57L80.13,152h116a24,24,0,0,0,23.61-19.71l12.16-66.86A8,8,0,0,0,230.14,58.87ZM104,204a12,12,0,1,1-12-12A12,12,0,0,1,104,204Zm96,0a12,12,0,1,1-12-12A12,12,0,0,1,200,204Zm4-74.57A8,8,0,0,1,196.1,136H77.22L65.59,72H214.41Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return shoppingCartCache!!
            }
        private var shoppingCartCache: ImageVector? = null

        val ShareNetwork: ImageVector
            get() {
                if (shareNetworkCache != null) {
                    return shareNetworkCache!!
                }
                shareNetworkCache = buildPhosphorIcon(
                    name = "ShareNetwork",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M176,160a39.89,39.89,0,0,0-28.62,12.09l-46.1-29.63a39.8,39.8,0,0,0,0-28.92l46.1-29.63a40,40,0,1,0-8.66-13.45l-46.1,29.63a40,40,0,1,0,0,55.82l46.1,29.63A40,40,0,1,0,176,160Zm0-128a24,24,0,1,1-24,24A24,24,0,0,1,176,32ZM64,152a24,24,0,1,1,24-24A24,24,0,0,1,64,152Zm112,72a24,24,0,1,1,24-24A24,24,0,0,1,176,224Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return shareNetworkCache!!
            }
        private var shareNetworkCache: ImageVector? = null

        val SlidersHorizontal: ImageVector
            get() {
                if (slidersHorizontalCache != null) {
                    return slidersHorizontalCache!!
                }
                slidersHorizontalCache = buildPhosphorIcon(
                    name = "SlidersHorizontal",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M40,88H73a32,32,0,0,0,62,0h81a8,8,0,0,0,0-16H135a32,32,0,0,0-62,0H40a8,8,0,0,0,0,16Zm64-24A16,16,0,1,1,88,80,16,16,0,0,1,104,64ZM216,168H199a32,32,0,0,0-62,0H40a8,8,0,0,0,0,16h97a32,32,0,0,0,62,0h17a8,8,0,0,0,0-16Zm-48,24a16,16,0,1,1,16-16A16,16,0,0,1,168,192Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return slidersHorizontalCache!!
            }
        private var slidersHorizontalCache: ImageVector? = null

        val Sparkle: ImageVector
            get() {
                if (sparkleCache != null) {
                    return sparkleCache!!
                }
                sparkleCache = buildPhosphorIcon(
                    name = "Sparkle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M197.58,129.06,146,110l-19-51.62a15.92,15.92,0,0,0-29.88,0L78,110l-51.62,19a15.92,15.92,0,0,0,0,29.88L78,178l19,51.62a15.92,15.92,0,0,0,29.88,0L146,178l51.62-19a15.92,15.92,0,0,0,0-29.88ZM137,164.22a8,8,0,0,0-4.74,4.74L112,223.85,91.78,169A8,8,0,0,0,87,164.22L32.15,144,87,123.78A8,8,0,0,0,91.78,119L112,64.15,132.22,119a8,8,0,0,0,4.74,4.74L191.85,144ZM144,40a8,8,0,0,1,8-8h16V16a8,8,0,0,1,16,0V32h16a8,8,0,0,1,0,16H184V64a8,8,0,0,1-16,0V48H152A8,8,0,0,1,144,40ZM248,88a8,8,0,0,1-8,8h-8v8a8,8,0,0,1-16,0V96h-8a8,8,0,0,1,0-16h8V72a8,8,0,0,1,16,0v8h8A8,8,0,0,1,248,88Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return sparkleCache!!
            }
        private var sparkleCache: ImageVector? = null

        val Star: ImageVector
            get() {
                if (starCache != null) {
                    return starCache!!
                }
                starCache = buildPhosphorIcon(
                    name = "Star",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M239.18,97.26A16.38,16.38,0,0,0,224.92,86l-59-4.76L143.14,26.15a16.36,16.36,0,0,0-30.27,0L90.11,81.23,31.08,86a16.46,16.46,0,0,0-9.37,28.86l45,38.83L53,211.75a16.38,16.38,0,0,0,24.5,17.82L128,198.49l50.53,31.08A16.4,16.4,0,0,0,203,211.75l-13.76-58.07,45-38.83A16.43,16.43,0,0,0,239.18,97.26Zm-15.34,5.47-48.7,42a8,8,0,0,0-2.56,7.91l14.88,62.8a.37.37,0,0,1-.17.48c-.18.14-.23.11-.38,0l-54.72-33.65a8,8,0,0,0-8.38,0L69.09,215.94c-.15.09-.19.12-.38,0a.37.37,0,0,1-.17-.48l14.88-62.8a8,8,0,0,0-2.56-7.91l-48.7-42c-.12-.1-.23-.19-.13-.5s.18-.27.33-.29l63.92-5.16A8,8,0,0,0,103,91.86l24.62-59.61c.08-.17.11-.25.35-.25s.27.08.35.25L153,91.86a8,8,0,0,0,6.75,4.92l63.92,5.16c.15,0,.24,0,.33.29S224,102.63,223.84,102.73Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return starCache!!
            }
        private var starCache: ImageVector? = null

        val Tag: ImageVector
            get() {
                if (tagCache != null) {
                    return tagCache!!
                }
                tagCache = buildPhosphorIcon(
                    name = "Tag",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M243.31,136,144,36.69A15.86,15.86,0,0,0,132.69,32H40a8,8,0,0,0-8,8v92.69A15.86,15.86,0,0,0,36.69,144L136,243.31a16,16,0,0,0,22.63,0l84.68-84.68a16,16,0,0,0,0-22.63Zm-96,96L48,132.69V48h84.69L232,147.31ZM96,84A12,12,0,1,1,84,72,12,12,0,0,1,96,84Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return tagCache!!
            }
        private var tagCache: ImageVector? = null

        val Trash: ImageVector
            get() {
                if (trashCache != null) {
                    return trashCache!!
                }
                trashCache = buildPhosphorIcon(
                    name = "Trash",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M216,48H176V40a24,24,0,0,0-24-24H104A24,24,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM96,40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8v8H96Zm96,168H64V64H192ZM112,104v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return trashCache!!
            }
        private var trashCache: ImageVector? = null

        val Truck: ImageVector
            get() {
                if (truckCache != null) {
                    return truckCache!!
                }
                truckCache = buildPhosphorIcon(
                    name = "Truck",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M255.42,117l-14-35A15.93,15.93,0,0,0,226.58,72H192V64a8,8,0,0,0-8-8H32A16,16,0,0,0,16,72V184a16,16,0,0,0,16,16H49a32,32,0,0,0,62,0h50a32,32,0,0,0,62,0h17a16,16,0,0,0,16-16V120A7.94,7.94,0,0,0,255.42,117ZM192,88h34.58l9.6,24H192ZM32,72H176v64H32ZM80,208a16,16,0,1,1,16-16A16,16,0,0,1,80,208Zm81-24H111a32,32,0,0,0-62,0H32V152H176v12.31A32.11,32.11,0,0,0,161,184Zm31,24a16,16,0,1,1,16-16A16,16,0,0,1,192,208Zm48-24H223a32.06,32.06,0,0,0-31-24V128h48Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return truckCache!!
            }
        private var truckCache: ImageVector? = null

        val UserCircle: ImageVector
            get() {
                if (userCircleCache != null) {
                    return userCircleCache!!
                }
                userCircleCache = buildPhosphorIcon(
                    name = "UserCircle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM74.08,197.5a64,64,0,0,1,107.84,0,87.83,87.83,0,0,1-107.84,0ZM96,120a32,32,0,1,1,32,32A32,32,0,0,1,96,120Zm97.76,66.41a79.66,79.66,0,0,0-36.06-28.75,48,48,0,1,0-59.4,0,79.66,79.66,0,0,0-36.06,28.75,88,88,0,1,1,131.52,0Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return userCircleCache!!
            }
        private var userCircleCache: ImageVector? = null

        val Users: ImageVector
            get() {
                if (usersCache != null) {
                    return usersCache!!
                }
                usersCache = buildPhosphorIcon(
                    name = "Users",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M117.25,157.92a60,60,0,1,0-66.5,0A95.83,95.83,0,0,0,3.53,195.63a8,8,0,1,0,13.4,8.74,80,80,0,0,1,134.14,0,8,8,0,0,0,13.4-8.74A95.83,95.83,0,0,0,117.25,157.92ZM40,108a44,44,0,1,1,44,44A44.05,44.05,0,0,1,40,108Zm210.14,98.7a8,8,0,0,1-11.07-2.33A79.83,79.83,0,0,0,172,168a8,8,0,0,1,0-16,44,44,0,1,0-16.34-84.87,8,8,0,1,1-5.94-14.85,60,60,0,0,1,55.53,105.64,95.83,95.83,0,0,1,47.22,37.71A8,8,0,0,1,250.14,206.7Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return usersCache!!
            }
        private var usersCache: ImageVector? = null

        val Wallet: ImageVector
            get() {
                if (walletCache != null) {
                    return walletCache!!
                }
                walletCache = buildPhosphorIcon(
                    name = "Wallet",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M216,64H56a8,8,0,0,1,0-16H192a8,8,0,0,0,0-16H56A24,24,0,0,0,32,56V184a24,24,0,0,0,24,24H216a16,16,0,0,0,16-16V80A16,16,0,0,0,216,64Zm0,128H56a8,8,0,0,1-8-8V78.63A23.84,23.84,0,0,0,56,80H216Zm-48-60a12,12,0,1,1,12,12A12,12,0,0,1,168,132Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return walletCache!!
            }
        private var walletCache: ImageVector? = null

        val WarningCircle: ImageVector
            get() {
                if (warningCircleCache != null) {
                    return warningCircleCache!!
                }
                warningCircleCache = buildPhosphorIcon(
                    name = "WarningCircle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm-8-80V80a8,8,0,0,1,16,0v56a8,8,0,0,1-16,0Zm20,36a12,12,0,1,1-12-12A12,12,0,0,1,140,172Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return warningCircleCache!!
            }
        private var warningCircleCache: ImageVector? = null

        val X: ImageVector
            get() {
                if (xCache != null) {
                    return xCache!!
                }
                xCache = buildPhosphorIcon(
                    name = "X",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return xCache!!
            }
        private var xCache: ImageVector? = null

        val XCircle: ImageVector
            get() {
                if (xCircleCache != null) {
                    return xCircleCache!!
                }
                xCircleCache = buildPhosphorIcon(
                    name = "XCircle",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = false,
                ) {
                    addPath(
                        pathData = addPathNodes("M165.66,101.66,139.31,128l26.35,26.34a8,8,0,0,1-11.32,11.32L128,139.31l-26.34,26.35a8,8,0,0,1-11.32-11.32L116.69,128,90.34,101.66a8,8,0,0,1,11.32-11.32L128,116.69l26.34-26.35a8,8,0,0,1,11.32,11.32ZM232,128A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return xCircleCache!!
            }
        private var xCircleCache: ImageVector? = null
    }

    object AutoMirrored {
        val ArrowLeft: ImageVector
            get() {
                if (arrowLeftCache != null) {
                    return arrowLeftCache!!
                }
                arrowLeftCache = buildPhosphorIcon(
                    name = "ArrowLeft",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,128a8,8,0,0,1-8,8H59.31l58.35,58.34a8,8,0,0,1-11.32,11.32l-72-72a8,8,0,0,1,0-11.32l72-72a8,8,0,0,1,11.32,11.32L59.31,120H216A8,8,0,0,1,224,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowLeftCache!!
            }
        private var arrowLeftCache: ImageVector? = null

        val ArrowRight: ImageVector
            get() {
                if (arrowRightCache != null) {
                    return arrowRightCache!!
                }
                arrowRightCache = buildPhosphorIcon(
                    name = "ArrowRight",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M221.66,133.66l-72,72a8,8,0,0,1-11.32-11.32L196.69,136H40a8,8,0,0,1,0-16H196.69L138.34,61.66a8,8,0,0,1,11.32-11.32l72,72A8,8,0,0,1,221.66,133.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowRightCache!!
            }
        private var arrowRightCache: ImageVector? = null

        val ArrowSquareOut: ImageVector
            get() {
                if (arrowSquareOutCache != null) {
                    return arrowSquareOutCache!!
                }
                arrowSquareOutCache = buildPhosphorIcon(
                    name = "ArrowSquareOut",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M224,104a8,8,0,0,1-16,0V59.32l-66.33,66.34a8,8,0,0,1-11.32-11.32L196.68,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return arrowSquareOutCache!!
            }
        private var arrowSquareOutCache: ImageVector? = null

        val CaretRight: ImageVector
            get() {
                if (caretRightCache != null) {
                    return caretRightCache!!
                }
                caretRightCache = buildPhosphorIcon(
                    name = "CaretRight",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M181.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L164.69,128,90.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,181.66,133.66Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return caretRightCache!!
            }
        private var caretRightCache: ImageVector? = null

        val PaperPlaneTilt: ImageVector
            get() {
                if (paperPlaneTiltCache != null) {
                    return paperPlaneTiltCache!!
                }
                paperPlaneTiltCache = buildPhosphorIcon(
                    name = "PaperPlaneTilt",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M227.32,28.68a16,16,0,0,0-15.66-4.08l-.15,0L19.57,82.84a16,16,0,0,0-2.49,29.8L102,154l41.3,84.87A15.86,15.86,0,0,0,157.74,248q.69,0,1.38-.06a15.88,15.88,0,0,0,14-11.51l58.2-191.94c0-.05,0-.1,0-.15A16,16,0,0,0,227.32,28.68ZM157.83,231.85l-.05.14,0-.07-40.06-82.3,48-48a8,8,0,0,0-11.31-11.31l-48,48L24.08,98.25l-.07,0,.14,0L216,40Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return paperPlaneTiltCache!!
            }
        private var paperPlaneTiltCache: ImageVector? = null

        val SignOut: ImageVector
            get() {
                if (signOutCache != null) {
                    return signOutCache!!
                }
                signOutCache = buildPhosphorIcon(
                    name = "SignOut",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M120,216a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V40a8,8,0,0,1,8-8h64a8,8,0,0,1,0,16H56V208h56A8,8,0,0,1,120,216Zm109.66-93.66-40-40a8,8,0,0,0-11.32,11.32L204.69,120H112a8,8,0,0,0,0,16h92.69l-26.35,26.34a8,8,0,0,0,11.32,11.32l40-40A8,8,0,0,0,229.66,122.34Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return signOutCache!!
            }
        private var signOutCache: ImageVector? = null

        val TrendDown: ImageVector
            get() {
                if (trendDownCache != null) {
                    return trendDownCache!!
                }
                trendDownCache = buildPhosphorIcon(
                    name = "TrendDown",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M240,128v64a8,8,0,0,1-8,8H168a8,8,0,0,1,0-16h44.69L136,107.31l-34.34,34.35a8,8,0,0,1-11.32,0l-72-72A8,8,0,0,1,29.66,58.34L96,124.69l34.34-34.35a8,8,0,0,1,11.32,0L224,172.69V128a8,8,0,0,1,16,0Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return trendDownCache!!
            }
        private var trendDownCache: ImageVector? = null

        val TrendUp: ImageVector
            get() {
                if (trendUpCache != null) {
                    return trendUpCache!!
                }
                trendUpCache = buildPhosphorIcon(
                    name = "TrendUp",
                    viewportWidth = 256f,
                    viewportHeight = 256f,
                    autoMirror = true,
                ) {
                    addPath(
                        pathData = addPathNodes("M240,56v64a8,8,0,0,1-16,0V75.31l-82.34,82.35a8,8,0,0,1-11.32,0L96,123.31,29.66,189.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0L136,140.69,212.69,64H168a8,8,0,0,1,0-16h64A8,8,0,0,1,240,56Z"),
                        pathFillType = PathFillType.NonZero,
                        fill = SolidColor(Color.Black),
                    )
                }
                return trendUpCache!!
            }
        private var trendUpCache: ImageVector? = null
    }
}

private fun buildPhosphorIcon(
    name: String,
    viewportWidth: Float,
    viewportHeight: Float,
    autoMirror: Boolean = false,
    block: ImageVector.Builder.() -> Unit,
): ImageVector = ImageVector.Builder(
    name = name,
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = viewportWidth,
    viewportHeight = viewportHeight,
    autoMirror = autoMirror,
).apply(block).build()

